In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [ ]:
dataset = pd.read_csv('/content/Customers - Customers.csv')
dataset.head()

CustomerID  Gender  Age  Annual Income ($)  Spending Score (1-100)  \
0           1    Male   19              15000                      39   
1           2    Male   21              35000                      81   
2           3  Female   20              86000                       6   
3           4  Female   23              59000                      77   
4           5  Female   31              38000                      40   

      Profession  Work Experience  Family Size  
0     Healthcare                1            4  
1       Engineer                3            3  
2       Engineer                1            1  
3         Lawyer                0            2  
4  Entertainment                2            6

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              2000 non-null   int64 
 1   Gender                  2000 non-null   object
 2   Age                     2000 non-null   int64 
 3   Annual Income ($)       2000 non-null   int64 
 4   Spending Score (1-100)  2000 non-null   int64 
 5   Profession              1965 non-null   object
 6   Work Experience         2000 non-null   int64 
 7   Family Size             2000 non-null   int64 
dtypes: int64(6), object(2)
memory usage: 125.1+ KB


In [ ]:
dataset.isnull().sum()

CustomerID                 0
Gender                     0
Age                        0
Annual Income ($)          0
Spending Score (1-100)     0
Profession                35
Work Experience            0
Family Size                0
dtype: int64

In [ ]:
dataset.dropna(how = 'any', subset = ['Profession'], inplace = True)

In [ ]:
dataset.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income ($)         0
Spending Score (1-100)    0
Profession                0
Work Experience           0
Family Size               0
dtype: int64

In [ ]:
x = dataset[['Age', 'Annual Income ($)', 'Spending Score (1-100)', 'Work Experience']]
y = dataset[['Profession']]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, train_size = 0.8, random_state = 42)

In [ ]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
model = KNeighborsClassifier(n_neighbors = 5)
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
y_predict = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))
print(accuracy_score(y_test, y_predict)*100)

[[72 12  6  3  4 17  0  2  0]
 [20  1  0  5  2  3  1  0  0]
 [19  5  3  4  3  4  1  0  0]
 [30  3  1  5  2  5  1  1  0]
 [21  2  0  1  0  5  1  0  0]
 [34  5  4 10  3 11  1  1  1]
 [ 7  0  3  0  2  4  0  0  0]
 [18  2  0  2  0  2  0  0  0]
 [ 9  2  2  2  2  1  0  0  0]]
               precision    recall  f1-score   support

       Artist       0.31      0.62      0.42       116
       Doctor       0.03      0.03      0.03        32
     Engineer       0.16      0.08      0.10        39
Entertainment       0.16      0.10      0.12        48
    Executive       0.00      0.00      0.00        30
   Healthcare       0.21      0.16      0.18        70
    Homemaker       0.00      0.00      0.00        16
       Lawyer       0.00      0.00      0.00        24
    Marketing       0.00      0.00      0.00        18

     accuracy                           0.23       393
    macro avg       0.10      0.11      0.10       393
 weighted avg       0.17      0.23      0.18       393

23.40966921

In [ ]:
sam1 = [[22, 85000, 50, 4]]
print(model.predict(sam1))

['Artist']


In [ ]:
sam2 = [[31, 38000, 40, 5]]
print(model.predict(sam2))

['Doctor']


In [ ]:
sam3 = [[22, 90000, 6, 2]]
print(model.predict(sam3))

['Artist']
